// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://srvbmozptaycwxowzrpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNydmJtb3pwdGF5Y3d4b3d6cnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MTE3NjcsImV4cCI6MjA3Nzk4Nzc2N30.rMsFYuuL0zH6r6_NWaTqd2VtvDC1o1mAZn7EH-chxTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);